### PR TITLE
bug fix for compute soundspeed polytropic eos.h

### PR DESCRIPTION
**Pull request by korobkin**
critical bug in the new expression for soundspeed in polytropic and piecewise polytropic eos

### CODE REVIEW

**Review by hlim88 — COMMENTED** [review]
What is `A` in `@brief` such that `cs = sqrt{A*\Gamma\rho^(\Gamma-1) }`
But I cannot see it actual code
```
  static void compute_soundspeed(body & particle) {
    const double rho = particle.getDensity(),
                           K = particle.getAdiabatic();
    double soundspeed = sqrt(K*poly_gamma*pow(rho, poly_gamma - 1.));
    particle.setSoundspeed(soundspeed);
}
```

**Comment by Yurlungur** [comment]
This bug might be in nubhlight too... As I think you got those expression from me.

**Comment by hlim88** [comment]
@Yurlungur Yeah maybe. I think that analytic expressions mostly came from usual literatures but this is good to check.

**Comment by korobkin** [comment]
A is a different notation for K in the polytropic equation: P = K\rho^\Gamma, or A\rho^\Gamma

**Review by JulienLoiseau — APPROVED** [review]

**Review by JulienLoiseau — APPROVED** [review]

**Pull request merged**
