### PR TITLE
(+-*) a few recent updates

### PR DESCRIPTION
**Pull request by korobkin**

### CODE REVIEW

**Comment by junghans** [comment]
Sorry, what is the point of the `(+-*)` prefix?

**Comment by hlim88** [comment]
> Sorry, what is the point of the `(+-*)` prefix?

(+), (-) and (*) mean "complete", "not complete" or "in progress" respectively.
(these are the conventions that Oleg (and some other people) uses)

**Comment by korobkin** [comment]
> Sorry, what is the point of the `(+-*)` prefix?

I use "(+)", "(-)" and "(*)" instead of "added", "removed" and "changed", to save space in the first git commit line, which is only 50 characters. This case is clearly not the best example of this otherwise very convenient practice...

**Comment by junghans** [comment]
> > Sorry, what is the point of the `(+-*)` prefix?
> 
> I use "(+)", "(-)" and "(*)" instead of "added", "removed" and "changed", to save space in the first git commit line, which is only 50 characters. This case is clearly not the best example of this otherwise very convenient practice...

Are there stat include in header of each PR anyhow? And doesn't `git log --stat` do exactly that?

**Comment by korobkin** [comment]
> > > Sorry, what is the point of the `(+-*)` prefix?
> > 
> > 
> > I use "(+)", "(-)" and "(*)" instead of "added", "removed" and "changed", to save space in the first git commit line, which is only 50 characters. This case is clearly not the best example of this otherwise very convenient practice...
> 
> Aren't these stats included in header of each PR anyhow? And doesn't `git log --stat` do exactly that?

Of course, but the point here is to save space in the git commit line. For example, instead of writing "added module X which does blah", I write "(+) module X which does blah", because in the first case "blah" could've been cut by git due to 50/72 format rule.

**Comment by korobkin** [comment]
We need to update docker containers to a more recent version of Ubuntu.

**Pull request merged**
